name: 'Docker image'
description: 'Builds and publishes a Docker image to Amazon ECR.'
inputs:
  aws-access-key-id:
    description: >
      AWS Access Key ID.
    required: true
  aws-secret-access-key:
    description: >
      AWS Secret Access Key.
    required: true
  aws-region:
    description: >
      AWS Region.
    default: eu-west-3
    required: false
  repository:
    description: >
      AWS ECR registry repository.
    required: true
  tag:
    description: >
      Image tag.
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ inputs.tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      shell: bash

    - name: Log out of Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
      shell: bash